name: Jamie Folsom
markdown: redcarpet
pygments: true
permalink: pretty
prose:
  rooturl: '_posts'
  siteurl: "http://jamiefolsom.github.io/"
  relativeLinks: 'http://jamiefolsom.github.io/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Type"
          options:
            - name: "News"
              value: "news"
            - name: "Opinion"
              value: "opinion"
            - name: "Investigation"
              value: "investigation"
      - name: "layout"
        field:
          element: "select"
          label: "Choose layout"
          options:
            - name: "Default"
              value: "default"
            - name: "Post"
              value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Newspaper Section(s)"
          placeholder: "Choose section(s) of the paper"
          options:
            - name: "Politics"
              value: "politics"
            - name: "Sports"
              value: "sports"
            - name: "Media"
              value: "media"
            - name: "Metro"
              value: "metro"

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
